POST http://localhost:3000/styles
Content-Type: application/json

{
  "nickname": "로맨틱무드",
  "title": "로맨틱 원피스 코디",
  "content": "하늘하늘한 소재의 원피스로 여성스러움을 강조했어요",
  "password": "romantic_dress_pw",
  "categories": {
    "dress": {
      "name": "쉬폰 롱 원피스",
      "brand": "에잇세컨즈",
      "price": 79900
    },
    "shoes": {
      "name": "스틸레토 힐",
      "brand": "사뿐",
      "price": 52000
    },
    "bag": {
      "name": "체인 미니백",
      "brand": "루이까또즈",
      "price": 190000
    },
    "accessory": {
      "name": "진주 귀걸이",
      "brand": "제이에스티나",
      "price": 60000
    }
  },
  "tags": [
    "로맨틱룩",
    "특별한날",
    "여신원피스"
  ],
  "imageUrls": [
    "https://example.com/images/romantic_dress.jpg",
    "https://example.com/images/earrings_and_bag.jpg"
  ]
}

###
POST http://localhost:3000/styles
Content-Type: application/json

{
  "nickname": "커리어우먼",
  "title": "클래식하면서도 세련된 오피스 스타일",
  "content": "단정한 블라우스와 슬랙스를 매치해 전문적인 이미지를 강조했어요. 가벼운 아우터와 숄더백으로 포인트를 주어 세련미를 더했답니다.",
  "password": "office_style_pw",
  "categories": {
    "bag": {
      "name": "체인 ",
      "brand": "까또즈",
      "price": 390000
    },
    "accessory": {
      "name": "진주",
      "brand": "스티나",
      "price": 6000
    }
  },
  "tags": [
    "로맨틱룩",
    "오피스",
    "깔끔함"
  ],
  "imageUrls": [
    "https://example.com/images/office_look.jpg",
    "https://example.com/images/bag_and_watch.jpg"
  ]
}
###
PUT http://localhost:3000/styles/7
Content-Type: application/json

{
  "nickname": "수정맨",
  "title": "수정 메소드로 바뀐 제목",
  "content": "그런건 없다",
  "password": "romantic_dress_pw",
  "categories": {
      "shoes": {
      "name": "구두",
      "brand": "캬",
      "price": 6200
    },
    "bag": {
      "name": "백은 무슨 백이야",
      "brand": "버그",
      "price": 1500
    }  
  },
  "tags": [
    "테스트1",
    "오피스",
    "테스트2"
  ],
  "imageUrls": [
    "https://example.com/images/office_look.jpg",
    "https://example.com/images/bag_and_watch.jpg"
  ]
}

###
DELETE http://localhost:3000/styles/7
Content-Type: application/json

{
  "password": "romantic_dress_pw"
}

###
GET http://localhost:3000/styles

###
GET http://localhost:3000/styles?sortBy=mostViewed

###
GET http://localhost:3000/styles?sortBy=mostCurated

###
GET http://localhost:3000/styles?sortBy=mostViewed&searchBy=nickname&keyword=로맨틱

###
GET http://localhost:3000/styles?sortBy=mostViewed&searchBy=content&keyword=하늘하늘

###
GET http://localhost:3000/styles?sortBy=mostViewed&searchBy=tag&keyword=페미닌

###
GET http://localhost:3000/styles?sortBy=mostViewed&searchBy=title&keyword=코디